In [ ]:
#Scikit Learn Library 

Scikit-learn (Sklearn) is the most useful and robust library for machine learning in Python. It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python. This library, which is largely written in Python, is built upon NumPy, SciPy and Matplotlib.

In [ ]:
#Import the relevant libraries and read the dataset

In [1]:
import numpy as np

import matplotlib as plt

from sklearn import datasets #various toy datasets 

from sklearn import metrics #Check accuracy of model 

from sklearn.linear_model import LogisticRegression #various supervised and unsupervised learning algorithms

Dataset Loading 

In [2]:
iris = datasets.load_iris()

**Features**− The variables of data are called its features. They are also known as predictors, inputs or attributes.

**Feature matrix** − It is the collection of features, in case there are more than one.

**Feature Names** − It is the list of all the names of the features.

**Response** − It is the output variable that basically depends upon the feature variables. They are also known as target, label or output.

**Response Vector** − It is used to represent response column. Generally, we have just one response column.

**Target Names**− It represent the possible values taken by a response vector.

In [3]:
X = iris.data
y= iris.target

feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)
print("\nFirst 10 rows of X:\n", X[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


To check the accuracy of our model, we can split the dataset into two pieces-a training set and a testing set. Use the training set to train the model and testing set to test the model. After that, we can evaluate how well our model did.

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size = 0.4, random_state=1
)

**Exercise:** Perform the above steps on any other dataset available in Sklearn library.